import React from "react";
import Select from "react-select";

const options = [
  { value: "crema-aloe", label: "Crema de Aloe Vera" },
  { value: "jabón-menta", label: "Jabón de Menta" },
  { value: "crema-avena", label: "Crema de Avena" },
  { value: "jabón-lavanda", label: "Jabón de Lavanda" },
  { value: "crema-rosas", label: "Crema de Rosas" },
  { value: "jabón-coco", label: "Jabón de Coco" },
  { value: "aceite-argan", label: "Aceite de Argan" },
  { value: "crema-cafe", label: "Crema de Café" },
  { value: "jabón-rosa", label: "Jabón de Rosa Mosqueta" },
  { value: "serum-vitamina-c", label: "Serum de Vitamina C" },
  { value: "crema-vitamina-e", label: "Crema de Vitamina E" },
  { value: "jabón-aceite-de-oliva", label: "Jabón de Aceite de Oliva" },
  { value: "mascarilla-arcilla", label: "Mascarilla de Arcilla" },
  { value: "crema-miel", label: "Crema de Miel" },
  { value: "jabón-aceite-de-jojoba", label: "Jabón de Aceite de Jojoba" },
  { value: "crema-cocoa", label: "Crema de Cacao" },
  { value: "jabón-cítricos", label: "Jabón de Cítricos" },
  { value: "serum-hialuronico", label: "Serum de Ácido Hialurónico" },
  { value: "crema-de-pétalos", label: "Crema de Pétalos de Rosa" },
  { value: "jabón-de-agua-termal", label: "Jabón de Agua Termal" },
  { value: "crema-papaya", label: "Crema de Papaya" },
  { value: "jabón-de-coco-y-almendras", label: "Jabón de Coco y Almendras" },
  { value: "aceite-de-rosa-mosqueta", label: "Aceite de Rosa Mosqueta" },
  { value: "crema-antiarrugas", label: "Crema Antiarrugas" },
  { value: "jabón-de-hierbas", label: "Jabón de Hierbas" },
  { value: "crema-de-menta", label: "Crema de Menta" },
  { value: "jabón-de-arroz", label: "Jabón de Arroz" },
  {
    value: "mascarilla-de-aceite-de-argan",
    label: "Mascarilla de Aceite de Argan",
  },
  { value: "crema-de-té-verde", label: "Crema de Té Verde" },
  { value: "jabón-de-naranja", label: "Jabón de Naranja" },
  { value: "serum-reparador", label: "Serum Reparador" },
  { value: "crema-limpiadora", label: "Crema Limpiadora" },
  { value: "jabón-de-menta-y-eucalipto", label: "Jabón de Menta y Eucalipto" },
  { value: "crema-de-aceite-de-coco", label: "Crema de Aceite de Coco" },
  { value: "aceite-de-lavanda", label: "Aceite de Lavanda" },
  { value: "jabón-de-cedro", label: "Jabón de Cedro" },
  { value: "serum-antiacne", label: "Serum Antiacné" },
  { value: "crema-de-caléndula", label: "Crema de Caléndula" },
  { value: "jabón-de-manuka", label: "Jabón de Manuka" },
  { value: "aceite-de-melaleuca", label: "Aceite de Melaleuca" },
  { value: "crema-para-el-cuerpo", label: "Crema Corporal" },
  { value: "jabón-de-ciprés", label: "Jabón de Ciprés" },
  { value: "mascarilla-de-avena", label: "Mascarilla de Avena" },
  { value: "serum-reafirmante", label: "Serum Reafirmante" },
  { value: "crema-de-caviar", label: "Crema de Caviar" },
  { value: "jabón-de-ginseng", label: "Jabón de Ginseng" },
  { value: "aceite-de-cáñamo", label: "Aceite de Cáñamo" },
  { value: "crema-de-papaya-y-coco", label: "Crema de Papaya y Coco" },
  { value: "jabón-de-kiwi", label: "Jabón de Kiwi" },
  { value: "serum-anti-envejecimiento", label: "Serum Anti-envejecimiento" },
  { value: "crema-de-exfoliación", label: "Crema Exfoliante" },
  { value: "jabón-de-azúcar", label: "Jabón de Azúcar" },
  { value: "aceite-de-mango", label: "Aceite de Mango" },
  { value: "crema-de-shea", label: "Crema de Karité" },
];

const Buscador = () => (
  <Select options={options} placeholder="¿Qué buscas hoy?" />
);
export default Buscador;
