# Generated by Django 5.1.3 on 2024-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='beneficios',
            field=models.TextField(default='No especificado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.TextField(default='No especificado'),
            preserve_default=False,
        ),
    ]
