# Generated by Django 5.1.3 on 2024-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='beneficios',
            field=models.JSONField(default=list),
        ),
    ]
