# Generated by Django 5.1.3 on 2024-12-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_ingredientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
