# Generated by Django 5.1.3 on 2024-12-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_producto_beneficios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('img_dia', models.ImageField(blank=True, null=True, upload_to='kits/dia/')),
                ('kit_dia', models.JSONField(default=list)),
                ('parrafo_dia', models.TextField()),
                ('img_noche', models.ImageField(blank=True, null=True, upload_to='kits/noche/')),
                ('kit_noche', models.JSONField(default=list)),
                ('parrafo_noche', models.TextField()),
            ],
        ),
    ]
