# Generated by Django 5.1.3 on 2024-12-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción predeterminada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='beneficios',
            field=models.JSONField(default=list),
        ),
    ]
