# Generated by Django 5.1.3 on 2024-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_descripcion_alter_producto_beneficios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dia', models.JSONField(default=dict)),
                ('noche', models.JSONField(default=dict)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
