# Generated by Django 5.1.3 on 2024-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_parrafo_dia_kit_decripcion_noche_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='beneficios',
            new_name='beneficios_dia',
        ),
        migrations.RenameField(
            model_name='kit',
            old_name='precio',
            new_name='precio_dia',
        ),
        migrations.AddField(
            model_name='kit',
            name='beneficios_noche',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='kit',
            name='precio_noche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
