# Generated by Django 5.1.3 on 2024-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitnoche',
            fields=[
                ('id_kit', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dia', models.JSONField(default=dict)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='kit',
            name='noche',
        ),
    ]
