# Generated by Django 5.1.3 on 2024-12-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_kitnoche_remove_kit_noche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitnoche',
        ),
        migrations.AddField(
            model_name='kit',
            name='noche',
            field=models.JSONField(default=dict),
        ),
    ]
