# Generated by Django 5.1.3 on 2024-12-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_decripcion_noche_kit_descripcion_noche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='nombre',
            new_name='nombre_dia',
        ),
        migrations.AddField(
            model_name='kit',
            name='nombre_noche',
            field=models.CharField(default='escribe un nombre', max_length=100),
            preserve_default=False,
        ),
    ]
